wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.12
    start_time: 1647204531
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 40
      - 41
      - 49
      3:
      - 1
      - 7
      4: 3.8.12
      5: 0.12.11
      6: 4.12.5
      8:
      - 1
      - 5
